version: "3.7"
services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file: .docker.env
  db:
    image: cassandra
    restart: always
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    volumes:
      - db-data:/var/lib/cassandra
volumes:
  db-data: