version: "3.7"
services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file: .env
  db:
    image: cassandra
    restart: always
    ports:
      - "7000:7000"
    volumes:
      - db-data:/var/lib/cassandra
volumes:
  db-data: