server:
  host: localhost
  port: :3000
cassandra:
  host: localhost
  port: 9042
  key_space: tinyurl
jwt:
  secret: quy3npk1996
  issuer: quyenpk
redis:
  host: localhost
  port: 6379
  addr: localhost:6379